theme: jekyll-theme-minimal
title: "Tech Notes"
description: "For keeping notes on tech stuffs"
url: "https://shahincsejnu.github.io/tech-notes"
baseurl: ""

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .git
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
  - _site
  - .bundle
